apps/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('blog/', views.home_blog, name='home_blog'),
    path('blog/busqueda/', views.busqueda_palabra_clave, name='busqueda_palabra_clave'),
    path('blog/categoria/<slug:slug>',views.filtro_categoria, name='filtro_categoria'),
    path('blog/post/<slug:slug>',views.single_post, name='single_post'),
    path('blog/post/post-comment/',views.post_comment, name='post_comment'),
    ]
    

biocompras/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.blog.urls')),
    path('', include('apps.carrito.urls')),
    path('vendors/', include('apps.tiendas.urls')),
    path('users/', include('apps.usuarios.urls')),
]

apps/blog/models.py
import os
from django.contrib.auth import get_user_model 
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible

User = get_user_model() 

class TimeStampModel(models.Model):

	user = models.ForeignKey(User, db_index=True, null=True, blank=True, on_delete=models.CASCADE)
	description = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	modified = models.DateTimeField(auto_now = True)

	class Meta:
		abstract = True 

class Categoria(models.Model):

	nombre = models.CharField(max_length=40)
	slug = models.SlugField(editable = False, unique=True, null=True, blank=True, max_length=255)

	def __str__(self):
		return "{0}".format(self.nombre)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.nombre)
		super(Categoria, self).save(*args,**kwargs)
		
def upload_imagen_post(instance, filename):
        filename_base, filename_ext = os.path.splitext(filename)
        return 'blog/post/{0}/img/{1}{2}'.format(instance.slug,filename_base,filename_ext.lower())


class Post(TimeStampModel): 

	imagen = models.ImageField(upload_to=upload_imagen_post, blank=True)
	titulo = models.CharField(max_length=400, editable = True)
	categoria = models.ManyToManyField(Categoria)
	slug = models.SlugField(editable = True, unique=True, null=True, blank=True,max_length=400)
	vistas = models.BigIntegerField(default=0)
	descripcion_corta = models.CharField(max_length=200)
	
	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.titulo)
		super(Post, self).save(*args,**kwargs)

	def __str__(self):
		return "{0}".format(self.titulo)

class Comment(models.Model):

	user = models.CharField(max_length=500, blank=False)
	email = models.CharField(max_length=500, blank=False)
	description = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return "{0} - {1} - {2}".format(self.post.titulo, self.user, self.email)

apps/blog/views.py
from django.shortcuts import render, redirect
from .models import *
from django.views.generic import ListView, CreateView, DetailView
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
try:
    from django.utils import simplejson as json
except ImportError:
    import json
from django.db.models import Q
 

def home_blog(request):
 
    publicaciones = Post.objects.all() 
    paginator = Paginator(publicaciones, 5) # Show 25 contacts per page

    page = request.GET.get('page')
    posts = paginator.get_page(page)

    categories = Categoria.objects.all()

    return render(request,'blog/index.html',{'posts':posts,'categories':categories})

def busqueda_palabra_clave(request):

	categories = Categoria.objects.all()

	busqueda = request.GET.get('busqueda')
		
	publicaciones = Post.objects.filter(
		Q(titulo__icontains=busqueda)
		| Q(categoria__nombre__icontains=busqueda)			
		).distinct()

	paginator = Paginator(publicaciones, 5)
	try:
		page = request.GET['page']
	except:
		page = 1
	posts = paginator.get_page(page)	

	return render(request,'blog/busqueda-palabra-clave.html',{'posts':posts
		,'busqueda':busqueda,'categories':categories})

def filtro_categoria(request, *args, **kwargs):

	categories = Categoria.objects.all()

	category = Categoria.objects.get(slug=kwargs.get('slug'))
		
	publicaciones = Post.objects.filter(categoria__id=category.id)

	paginator = Paginator(publicaciones, 5)
	try:
		page = request.GET['page']
	except:
		page = 1
	posts = paginator.get_page(page)

	return render(request,'blog/busqueda-categoria.html',{'posts':posts
		,'category':category,'categories':categories})

def single_post(request, *args, **kwargs):
 	list_posts = []
 	post = Post.objects.get(slug=kwargs.get('slug'))
 	categories_post = post.categoria.all()
 	for categoria in categories_post:
 		related_post = Post.objects.filter(categoria=categoria)
 		for pub in related_post:
 			if pub != post:
 				list_posts.append(pub)
 	categories = Categoria.objects.all()
 	comments = Comment.objects.filter(post__slug=kwargs.get('slug'))
 	print(list_posts)
 	return render(request,'blog/single-post.html',{'post':post
    	,'categories':categories
    	,'list_posts':list_posts
    	,'comments':comments})

@require_POST
def post_comment(request, *args, **kwargs):
	
	if request.method == 'POST':
		email = request.POST.get('email', None)
		user = request.POST.get('user', None)
		mensaje = request.POST.get('comment', None)
		slug = request.POST.get('slug', None)

		comment = Comment()
		comment.user = user
		comment.email = email
		comment.description = mensaje
		comment.post = Post.objects.get(slug = slug)
		comment.save()

		message = 'Su comentario se ha enviado!'

		ctx = {'message': message}
		
		return HttpResponse(json.dumps(ctx), content_type='application/json')

templates/blog/busqueda-categoria.html
{% extends "home/base.html" %}
{% load static %}{% load blogtag %}
{% load humanize %}
{% block content %}
      <div class="page-title">
        <div class="container">
          <div class="column">
            <h1>Blog | Categoría: {{category|upper}} ({{posts|length}})</h1>
          </div>
          <div class="column">
            <ul class="breadcrumbs">
              <li><a href="{% url 'home_compradores' %}">Inicio</a>
              </li>
              <li class="separator">&nbsp;</li>
              <li>Blog</li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Page Content-->
      <div class="container padding-bottom-3x mb-1">
        <div class="row">
          <!-- Blog Posts-->
          <div class="col-xl-9 col-lg-8">
            {% for post in posts  %} 
            <br>         
            <!-- Post-->
            <article class="row">
              <div class="col-md-3">
                <ul class="post-meta">
                  <li><i class="icon-clock"></i><a href="blog-single-rs.html">&nbsp;{{post.created|date:"d M Y"}}</a></li>
                  <li><i class="icon-head"></i>&nbsp;{{post.user}}</li>
                  <li><i class="icon-tag"></i>
                    {% for categoria in post.categoria.all %}
                      {% if post.categoria.count == 1 %}
                          <a href="#">&nbsp;{{categoria.nombre}}</a>
                      {% elif forloop.first %}
                          <a href="#">&nbsp;{{categoria.nombre}},</a>
                      {% elif forloop.last %}
                      <a href="#">&nbsp;{{categoria.nombre}}</a>
                      {% endif %}
                      
                    {% endfor %}
                  </li>
                  <li><i class="icon-speech-bubble"></i><a href="#">&nbsp;0 Comments</a></li>
                </ul>
              </div>              
              <div class="col-md-9 blog-post">
                <h3 class="post-title text-center"><a href="blog-single-rs.html">{{post.titulo|upper}}</a></h3>
                <a class="post-thumb" href="blog-single-rs.html"><img class="img img-responsive" src="{{post.imagen.url}}" alt="Post"></a>                
                <p>{{post.description|safe|truncatewords:"50"}} <a href='blog-single-rs.html' class='text-medium'>Leer más...</a></p>
              </div>
            </article>
            <!-- Post-->
            <hr>
            {% endfor %}
            
            <!-- Pagination-->
            <nav class="pagination">
              {% if posts.has_previous %}    
              <div class="column text-right hidden-xs-down"><a class="btn btn-outline-secondary btn-sm" href="?busqueda={{busqueda}}&page={{ posts.previous_page_number }}"><i class="icon-arrow-left"></i> Anterior&nbsp;</a></div>
              {% endif %}
              <div class="column text-center">
                <ul class="pages">
                  <li>Página</li>  
                  <li></li>
                  <li class="active"><a href="#">{{ posts.number }}</a></li>  
                  <li>de</li>               
                  <li>{{ posts.paginator.num_pages }}</li>
                </ul>
              </div>
              {% if posts.has_next %}
              <div class="column text-right hidden-xs-down"><a class="btn btn-outline-secondary btn-sm" href="/blog/busqueda/?busqueda={{busqueda}}&page={{ posts.next_page_number }}">Siguiente&nbsp;<i class="icon-arrow-right"></i></a></div>
              {% endif %}
            </nav>
          </div>
          <!-- Sidebar          -->
          <div class="col-xl-3 col-lg-4">
            <aside class="sidebar">
              <div class="padding-top-2x hidden-lg-up"></div>
              <!-- Widget Search-->
              <section class="widget">
                <form class="input-group form-group" method="GET" action="/blog/busqueda/">
                  <span class="input-group-btn">
                    <button type="submit"><i class="icon-search"></i></button>
                  </span>
                  <input class="form-control" name="busqueda" type="search" placeholder="Buscar por palabras clave">
                </form>
              </section>
              <!-- Widget Categories-->
              <section class="widget widget-categories">
                <h3 class="widget-title">Categorías</h3>
                <ul>
                  {% for categoria in categories  %}
                  <li><a href="{% url 'filtro_categoria' categoria.slug %}">{{categoria.nombre}}</a><span>({{categoria.post_set|get_count_posts}})</span></li>                    
                  {% endfor %}                                    
                </ul>
              </section>
            </aside>
          </div>
        </div>
      </div>
{% endblock %}

templates/blog/busqueda-palabra-clave.html
{% extends "home/base.html" %}
{% load static %}{% load blogtag %}
{% load humanize %}
{% block content %}
      <div class="page-title">
        <div class="container">
          <div class="column">
            <h1>Blog | Resultados a búsqueda: "{{busqueda}}" ({{posts|length}})</h1>
          </div>
          <div class="column">
            <ul class="breadcrumbs">
              <li><a href="{% url 'home_compradores' %}">Inicio</a>
              </li>
              <li class="separator">&nbsp;</li>
              <li>Blog</li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Page Content-->
      <div class="container padding-bottom-3x mb-1">
        <div class="row">
          <!-- Blog Posts-->
          <div class="col-xl-9 col-lg-8">
            {% for post in posts  %} 
            <br>         
            <!-- Post-->
            <article class="row">
              <div class="col-md-3">
                <ul class="post-meta">
                  <li><i class="icon-clock"></i><a href="blog-single-rs.html">&nbsp;{{post.created|date:"d M Y"}}</a></li>
                  <li><i class="icon-head"></i>&nbsp;{{post.user}}</li>
                  <li><i class="icon-tag"></i>
                    {% for categoria in post.categoria.all %}
                      {% if post.categoria.count == 1 %}
                          <a href="#">&nbsp;{{categoria.nombre}}</a>
                      {% elif forloop.first %}
                          <a href="#">&nbsp;{{categoria.nombre}},</a>
                      {% elif forloop.last %}
                      <a href="#">&nbsp;{{categoria.nombre}}</a>
                      {% endif %}
                      
                    {% endfor %}
                  </li>
                  <li><i class="icon-speech-bubble"></i><a href="#">&nbsp;0 Comments</a></li>
                </ul>
              </div>              
              <div class="col-md-9 blog-post">
                <h3 class="post-title text-center"><a href="blog-single-rs.html">{{post.titulo|upper}}</a></h3>
                <a class="post-thumb" href="blog-single-rs.html"><img class="img img-responsive" src="{{post.imagen.url}}" alt="Post"></a>                
                <p>{{post.description|safe|truncatewords:"50"}} <a href='blog-single-rs.html' class='text-medium'>Leer más...</a></p>
              </div>
            </article>
            <!-- Post-->
            <hr>
            {% endfor %}
            
            <!-- Pagination-->
            <nav class="pagination">
              {% if posts.has_previous %}    
              <div class="column text-right hidden-xs-down"><a class="btn btn-outline-secondary btn-sm" href="?busqueda={{busqueda}}&page={{ posts.previous_page_number }}"><i class="icon-arrow-left"></i> Anterior&nbsp;</a></div>
              {% endif %}
              <div class="column text-center">
                <ul class="pages">
                  <li>Página</li>  
                  <li></li>
                  <li class="active"><a href="#">{{ posts.number }}</a></li>  
                  <li>de</li>               
                  <li>{{ posts.paginator.num_pages }}</li>
                </ul>
              </div>
              {% if posts.has_next %}
              <div class="column text-right hidden-xs-down"><a class="btn btn-outline-secondary btn-sm" href="/blog/busqueda/?busqueda={{busqueda}}&page={{ posts.next_page_number }}">Siguiente&nbsp;<i class="icon-arrow-right"></i></a></div>
              {% endif %}
            </nav>
          </div>
          <!-- Sidebar          -->
          <div class="col-xl-3 col-lg-4">
            <aside class="sidebar">
              <div class="padding-top-2x hidden-lg-up"></div>
              <!-- Widget Search-->
              <section class="widget">
                <form class="input-group form-group" method="GET" action="/blog/busqueda/">
                  <span class="input-group-btn">
                    <button type="submit"><i class="icon-search"></i></button>
                  </span>
                  <input class="form-control" name="busqueda" type="search" placeholder="Buscar por palabras clave">
                </form>
              </section>
              <!-- Widget Categories-->
              <section class="widget widget-categories">
                <h3 class="widget-title">Categorías</h3>
                <ul>
                  {% for categoria in categories  %}
                  <li><a href="{% url 'filtro_categoria' categoria.slug %}">{{categoria.nombre}}</a><span>({{categoria.post_set|get_count_posts}})</span></li>                    
                  {% endfor %}                                    
                </ul>
              </section>
            </aside>
          </div>
        </div>
      </div>
{% endblock %}

templates/blog/index.html
{% extends "home/base.html" %}
{% load static %}{% load blogtag %}
{% load humanize %}
{% block content %}
      <div class="page-title">
        <div class="container">
          <div class="column">
            <h1>Blog</h1>
          </div>
          <div class="column">
            <ul class="breadcrumbs">
              <li><a href="{% url 'home_compradores' %}">Inicio</a>
              </li>
              <li class="separator">&nbsp;</li>
              <li>Blog</li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Page Content-->
      <div class="container padding-bottom-3x mb-1">
        <div class="row">
          <!-- Blog Posts-->
          <div class="col-xl-9 col-lg-8">
            {% for post in posts  %} 
            <br>         
            <!-- Post-->
            <article class="row">
              <div class="col-md-3">
                <ul class="post-meta">
                  <li><i class="icon-clock"></i><a href="blog-single-rs.html">&nbsp;{{post.created|date:"d M Y"}}</a></li>
                  <li><i class="icon-head"></i>&nbsp;{{post.user}}</li>
                  <li><i class="icon-tag"></i>
                    {% for categoria in post.categoria.all %}
                      {% if post.categoria.count == 1 %}
                          <a href="{% url 'filtro_categoria' categoria.slug %}">&nbsp;{{categoria.nombre}}</a>
                      {% elif forloop.first %}
                          <a href="{% url 'filtro_categoria' categoria.slug %}">&nbsp;{{categoria.nombre}},</a>
                      {% elif forloop.last %}
                      <a href="{% url 'filtro_categoria' categoria.slug %}">&nbsp;{{categoria.nombre}}</a>
                      {% endif %}
                      
                    {% endfor %}
                  </li>
                  <li><i class="icon-speech-bubble"></i><a href="#">&nbsp;0 Comments</a></li>
                </ul>
              </div>              
              <div class="col-md-9 blog-post">
                <h3 class="post-title text-center"><a href="{% url 'single_post' post.slug %}">{{post.titulo|upper}}</a></h3>
                <a class="post-thumb" href="{% url 'single_post' post.slug %}"><img class="img img-responsive" src="{{post.imagen.url}}" alt="Post"></a>                
                <p>{{post.description|safe|truncatewords:"50"}} <a href='{% url 'single_post' post.slug %}' class='text-medium'>Leer más...</a></p>
              </div>
            </article>
            <!-- Post-->
            <hr>
            {% endfor %}
            
            <!-- Pagination-->
            <nav class="pagination">
              {% if posts.has_previous %}    
              <div class="column text-right hidden-xs-down"><a class="btn btn-outline-secondary btn-sm" href="?page={{ posts.previous_page_number }}"><i class="icon-arrow-left"></i> Anterior&nbsp;</a></div>
              {% endif %}
              <div class="column text-center">
                <ul class="pages">
                  <li>Página</li>  
                  <li></li>
                  <li class="active"><a href="#">{{ posts.number }}</a></li>  
                  <li>de</li>               
                  <li><a href="#">{{ posts.paginator.num_pages }}</a></li>
                </ul>
              </div>
              {% if posts.has_next %}
              <div class="column text-right hidden-xs-down"><a class="btn btn-outline-secondary btn-sm" href="?page={{ posts.next_page_number }}">Siguiente&nbsp;<i class="icon-arrow-right"></i></a></div>
              {% endif %}
            </nav>
          </div>
          <!-- Sidebar          -->
          <div class="col-xl-3 col-lg-4">
            <aside class="sidebar">
              <div class="padding-top-2x hidden-lg-up"></div>
              <!-- Widget Search-->
              <section class="widget">
                <form class="input-group form-group" method="GET" action="/blog/busqueda/">
                  <span class="input-group-btn">
                    <button type="submit"><i class="icon-search"></i></button>
                  </span>
                  <input class="form-control" name="busqueda" type="search" placeholder="Buscar por palabras clave">
                </form>
              </section>
              <!-- Widget Categories-->
              <section class="widget widget-categories">
                <h3 class="widget-title">Categorías</h3>
                <ul>
                  {% for categoria in categories  %}
                  <li><a href="{% url 'filtro_categoria' categoria.slug %}">{{categoria.nombre}}</a><span>({{categoria.post_set|get_count_posts}})</span></li>                    
                  {% endfor %}                                    
                </ul>
              </section>
            </aside>
          </div>
        </div>
      </div>
{% endblock %}

templates/blog/single-post.html
{% extends "home/base.html" %}
{% load static %}{% load blogtag %}
{% load humanize %}
{% block content %}
<div class="page-title">
  <div class="container">
    <div class="column">
      <h1>{{post.titulo|upper}}</h1>
    </div>
    <div class="column">
      <ul class="breadcrumbs">
        <li><a href="{% url 'home_compradores' %}">Inicio</a>
        </li>
        <li class="separator">&nbsp;</li>
        <li><a href="{% url 'home_blog' %}">Blog</a>
        </li>
        <li class="separator">&nbsp;</li>
        <li>{{post.slug}}</li>
      </ul>
    </div>
  </div>
</div>
<!-- Page Content-->
<div class="container padding-bottom-3x mb-2">
  <div class="row justify-content-center">
    <!-- Content-->
    <div class="col-lg-10">
      <!-- Post-->
      <div class="single-post-meta">
        <div class="column">
          <div class="meta-link">Creado <span>por</span> {{post.user}}</div>
          <div class="meta-link"><span>en</span>
            {% for categoria in post.categoria.all  %}
            <a href="{% url 'filtro_categoria' categoria.slug %}">{{categoria.nombre}},</a>              
            {% endfor %}
            
            
          </div>
        </div>
        <div class="column">
          <div class="meta-link"><a href="#"><i class="icon-clock"></i>{{post.created|date:"d M Y"}}</a></div>
          <div class="meta-link"><a class="scroll-to" href="#comments"><i class="icon-speech-bubble"></i>3</a></div>
        </div>
      </div>
      
        <figure><img src="{{post.imagen.url}}" alt="Image">
        </figure>
       
      {{post.description|safe}}
      <div class="single-post-footer">

        <div class="column">
          <div class="entry-share"><span class="text-muted">Share post:</span>
            <div class="share-links"><a class="social-button shape-circle sb-facebook" href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="socicon-facebook"></i></a><a class="social-button shape-circle sb-twitter" href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="socicon-twitter"></i></a><a class="social-button shape-circle sb-instagram" href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="socicon-instagram"></i></a><a class="social-button shape-circle sb-google-plus" href="#" data-toggle="tooltip" data-placement="top" title="Google +"><i class="socicon-googleplus"></i></a></div>
          </div>
        </div>
      </div>

      <!-- Relevant Posts-->
      <h3 class="padding-top-3x padding-bottom-1x">También le podría gustar...</h3>
      <div class="owl-carousel" data-owl-carousel="{ &quot;nav&quot;: false, &quot;dots&quot;: true, &quot;loop&quot;: true, &quot;autoHeight&quot;: false, &quot;margin&quot;: 30, &quot;responsive&quot;: {&quot;0&quot;:{&quot;items&quot;:1},&quot;630&quot;:{&quot;items&quot;:2},&quot;991&quot;:{&quot;items&quot;:3},&quot;1200&quot;:{&quot;items&quot;:3}} }">
        
          {% for post in  list_posts %}
            <div class="widget widget-featured-posts">
              <div class="entry text-center">
                <a href="{% url 'single_post' post.slug %}"><img src="{{post.imagen.url}}" alt="Post" class="img img-responsive" width="100"></a>             
                  <h4 class="entry-title"><a href="{% url 'single_post' post.slug %}">{{post.titulo}}</a></h4><span class="entry-meta">por {{post.user}}</span>
              </div>
            </div>
          {% endfor %}
         
        
      </div>
      <!-- Comment Form--> 
      <h4 class="padding-top-2x padding-bottom-1x">Déjanos un comentario</h4>
      <form class="row" method="POST" id="form_comment">{% csrf_token %}
        <div class="col-sm-6">
          <div class="form-group">
            <label for="comment-name">Nombre</label>
            <input class="form-control form-control-rounded" name="user" type="text" id="user" placeholder="John Doe" required>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <label for="comment-email">E-mail</label>
            <input class="form-control form-control-rounded" name="email" type="email" id="email" placeholder="johndoe@email.com" required>
          </div>
        </div>
        <div class="col-12">
          <div class="form-group">
            <label for="comment-text">Comentario</label>
            <textarea class="form-control form-control-rounded" name="comment" rows="7" id="comment" placeholder="Escribe tu comentario aquí..." required></textarea>
          </div>
        </div>
        <div class="col-12 text-right">
          <button class="btn btn-pill btn-primary" type="submit" id="btn_comment">Enviar</button>
        </div>
      </form>      
      <!-- Comments-->
      <section class="padding-top-3x" id="comments">
        <h3 class="padding-bottom-1x">Comentarios</h3>
        {% for comment in comments  %}       
        <!-- Comment-->
        <div class="comment">          
          <div class="comment-body">
            <div class="comment-header">
              <h4 class="comment-title">{{comment.user}}</h4>
            </div>
            <p class="comment-text">{{comment.description}}</p>
            <div class="comment-footer">
              <div class="column"><span class="comment-meta">{{comment.created}}</span></div>      
            </div>
          </div>
        </div>
        {% endfor %}
        
      </section>
      
    </div>
  </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script>
$('#btn_comment').click(function(event){
  event.preventDefault(); 
    
  var user = $("#user").val();
  var email = $("#email").val();
  var comment = $("#comment").val();

  if (user=="" || email =="" || comment ==""){
    alert("Formulario invalido, Todos los campos son requeridos!");
  }else{  
    document.getElementById('btn_comment').disabled = true;
    $('#form_comment').trigger("reset");
      $.ajax({
               type: "POST",
               url: "{% url 'post_comment' %}",
               data: {'user' : user,
                'email': email,
                'comment':comment,
                'slug': '{{post.slug}}',
                'csrfmiddlewaretoken': '{{ csrf_token }}'
               },
               dataType: "json", 
               success: function(response) {
                alert(response.message);   
                location.reload();                
                },
                error: function(rs) {
                  alert(rs.responseText); 
                  location.reload();
                }
          }); 
  }
 
    })
</script>
{% endblock %}